###
GET localhost:8081/api/v1/users/auths
Accept: application/json

###
GET localhost:8081/api/v1/users/auths/2
Accept: application/json

###
POST localhost:8081/api/v1/users/auths
Content-Type: application/json

{
  "userId": 5,
  "email": "bogdan.yarovoy.01@example.com",
  "password": "12345678",
  "created": "2024-10-07T13:57:47.537+00:00",
  "changed": "2024-10-07T13:58:05.417+00:00",
  "isDeleted": false
}

###
PUT localhost:8081/api/v1/users/auths
Content-Type: application/json

{
  "id": 5,
  "email": "admin123@example.com",
  "password": "passssss2ed",
  "created": "2024-10-07T16:09:58.773+00:00",
  "changed": "2024-10-07T16:22:58.773+00:00",
  "isDeleted": false
}

###
DELETE localhost:8081/api/v1/users/auths/6

###