GET http://localhost:8081/api/v1/users/details
Accept: application/json

###
###
###

GET http://localhost:8081/api/v1/users/details/4
Accept: application/json

###
###
###

POST http://localhost:8081/api/v1/users/details
Content-Type: application/json

{
  "userId": 6,
  "firstname": "Jane",
  "lastname": "Smith",
  "patronymic": "Rogan",
  "sex": "FEMALE",
  "dateOfBirth": "1993-01-21",
  "phone": "+3809342342",
  "about": "I love programming."
}

###
###
###

PUT http://localhost:8081/api/v1/users/details
Content-Type: application/json

{
  "id": 6,
  "firstname": "Bohdan",
  "lastname": "Yarovyi",
  "patronymic": "Hello world",
  "sex": "MALE",
  "dateOfBirth": "2001-11-07",
  "phone": "097",
  "about": "HELLO, i`m Petter"
}

###
###
###

DELETE http://localhost:8081/api/v1/users/details/13
Accept: application/json

###
###
###