GET http://localhost:8081/api/v1/users
Accept: application/json

###
###
###

GET http://localhost:8081/api/v1/users/1
Accept: application/json

###
###
###

POST http://localhost:8081/api/v1/users
Content-Type: application/json

{
  "nickname": "mellanholica",
  "userDetail": {
    "firstname": null,
    "lastname": null,
    "patronymic": null,
    "sex": null,
    "dateOfBirth": "2001-11-07",
    "phone": "0971773438",
    "about": null
  },
  "userAuth": {
    "email": "bogdan.yarovoy.01@example.com",
    "password": "345465234543"
  },
  "roles": [
    {
      "name": "USERSSSS"
    }
  ]
}

###
###
###

PUT http://localhost:8081/api/v1/users
Content-Type: application/json

{
  "id": 6,
  "nickname": "mellanholica",
  "avatar": null,
  "created": "2024-10-11T03:34:15.010+00:00",
  "changed": null,
  "isDeleted": false,
  "userDetail": {
    "id": 14,
    "userId": 6,
    "firstname": "Homer",
    "lastname": "Smith",
    "patronymic": "Rogan",
    "sex": "FEMALE",
    "dateOfBirth": "1993-01-21",
    "phone": "+38093442",
    "about": "I love programming.",
    "created": "2024-10-11T06:32:51.079+00:00",
    "changed": null,
    "isDeleted": false
  },
  "userAuth": {
    "id": 7,
    "userId": 6,
    "email": "bogdan.yarovoy.01@example.com",
    "password": "31452",
    "created": "2024-10-11T06:34:34.376+00:00",
    "changed": null,
    "isDeleted": false
  },
  "roles": [
    {
      "id": 2,
      "name": "ADMIN"
    }
  ]
}

###
###
###

DELETE localhost:8081/api/v1/users/5
