server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/echo_user
    username: bodya
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
    show-sql: true
  # V__description.sql
  flyway:
    schemas: public