server:
  port: 8081

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    url: jdbc:postgresql://localhost:5432/echo_user
    username: bodya
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    show-sql: false
    generate-ddl: false
  flyway:
    enabled: true
    locations: classpath:db/migration

application:
  name: Echo
  path:
    avatars: app/avatars
  endpoint:
    root: /api/v1
    user: ${application.endpoint.root}/users
    auth: ${application.endpoint.user}/auths
    detail: ${application.endpoint.user}/details
    role: ${application.endpoint.user}/roles
    avatar: ${application.endpoint.user}/avatar